### ISSUE TITLE
Not working with "@angular/cli": "1.1.3"

### ISSUE THREAD

**Issue by armackey** [spali/ng2-movable#9] opened 2017-06-26 15:51 UTC
Hey,

Great module but currently facing a major issue.

ERROR in MovableModule is not an NgModule
webpack: Failed to compile.

I've tried 
- downgrading typescript to 2.0.9(the one used in demo).
- downgrading angular cli(which causes incompatibility problems with typescript)

It only works if I were to save a file and on reload it works fine. That method will not work with unit testing. More importantly, will not work in production. Any insight on a fix is much appreciated.

**Comment by spali** [comment] 2017-06-27 07:19
could you please share a reproducible demo of it somehow?
Never used angular-cli, so I'm a bit limited here.

**Comment by armackey** [comment] 2017-06-27 15:43
Unfortunately, I can't share at the moment. :/

**Comment by sivery** [comment] 2017-10-12 08:45
Hi @spali ,

I'm having the same issue but I can't share either. However, just creating a new project following angular current tutorial (that use angular-cli), importing the module and running ng serve should allow you to reproduce the issue.

This seems to be linked to the following issue:
https://github.com/angular/angular-cli/issues/3426

Apparently, you're module is missing a .metadata.json file to work correctly with the latest versions of angular-cli.

**Comment by spali** [comment] 2018-01-11 17:22
Could you please test the dev version 0.3.0.
because of the complete redesign (not the module itself, but the project there shouldn't be new bugs, but probably the project setup could contain bugs.
So please test and give feedback.

**Comment by spali** [comment] 2018-04-16 07:55
due no feedback, I close this issue

**Closed as completed by spali** 2018-04-16 07:55 UTC
Labels: bug, feedback required
